
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def accountPage(window):
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 322,
        width = 584,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        322.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        34.0,
        fill="#5D5FEF",
        outline="")

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        311.0,
        fill="#6D6B6B",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    from loginPage.loginPage import loginPage
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: loginPage(window),
        relief="flat"
    )
    button_1.place(
        x=228.0,
        y=235.0,
        width=140.0,
        height=37.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    from front_end_cud import deleteUser
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: deleteUser(window),
        relief="flat"
    )
    button_2.place(
        x=412.0,
        y=149.0,
        width=140.0,
        height=37.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    from updateUserPage.updateUserPage import updateUserPage
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: updateUserPage(window),
        relief="flat"
    )
    button_3.place(
        x=228.0,
        y=149.0,
        width=140.0,
        height=37.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    from viewUserPage.viewUserPage import viewUserPage
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: viewUserPage(window),
        relief="flat"
    )
    button_4.place(
        x=44.0,
        y=149.0,
        width=140.0,
        height=37.0
    )

    canvas.create_text(
        136.0,
        2.0,
        anchor="nw",
        text="Account",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    from browsePage.browsePage import browsePage
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: browsePage(window),
        relief="flat"
    )
    button_5.place(
        x=15.0,
        y=6.0,
        width=59.0,
        height=20.0
    )
    window.resizable(False, False)
    window.mainloop()
