
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from accountPage.accountPage import accountPage
from front_end_r import getTierLists


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def browsePage(window):
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 322,
        width = 584,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        322.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        34.0,
        fill="#5D5FEF",
        outline="")

    #shared lists
    # canvas.create_rectangle(
    #     313.0,
    #     56.0,
    #     568.0,
    #     299.0,
    #     fill="#999393",
    #     outline="")

    # canvas.create_text(
    #     318.0,
    #     41.0,
    #     anchor="nw",
    #     text="Shared Lists:",
    #     fill="#000000",
    #     font=("Inter", 12 * -1)
    # )

    #my lists
    canvas.create_rectangle(
        26.0,
        56.0,
        568.0,
        299.0,
        fill="#999393",
        outline="")

    def getButton(title):
        button = Button(
            text=title,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: viewListPage(window, title),
            relief="flat"
        )
        return button

    #generate list buttons
    from connections import tryConnections
    from front_end_cud import getUsername
    from viewListPage.viewListPage import viewListPage
    curYVal = 61

    temp = None
    tierLists = getTierLists(getUsername())
    if(tierLists == None):
        temp = canvas.create_text(
        184,
        61,
        anchor="nw",
        text="No connection to DB",
        fill="#000000",
        font=("Inter", 12 * -1)
        )
    else:
        for tierListTitle in tierLists:
            #print(tierListTitle)
            getButton(tierListTitle).place(
                x=184.0,
                y=curYVal,
                width=243.0,
                height=25.0
            )
            #update y val
            curYVal += 30
            
    canvas.create_text(
        29.0,
        41.0,
        anchor="nw",
        text="My Lists:",
        fill="#000000",
        font=("Inter", 12 * -1)
    )

    canvas.create_text(
        136.0,
        2.0,
        anchor="nw",
        text="Browse",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: accountPage(window),
        relief="flat"
    )
    button_1.place(
        x=509.0,
        y=7.0,
        width=59.0,
        height=21.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    from createListPage.createListPage import createListPage
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: createListPage(window),
        relief="flat"
    )
    button_2.place(
        x=15.0,
        y=6.0,
        width=59.0,
        height=20.0
    )

    button_3 = Button(
        text="Load",
        borderwidth=0,
        highlightthickness=0,
        command=lambda: browsePage(window),
        relief="flat"
    )
    button_3.place(
        x=500.0,
        y=270.0,
        width=59.0,
        height=20.0
    )
    window.resizable(False, False)
    window.mainloop()
