
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import glob
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Label, Tk, Canvas, Entry, Text, Button, PhotoImage, INSERT

from numpy import imag

from browsePage.browsePage import browsePage
from front_end_cud import getUsername
from front_end_r import getTierListByTitle
from util import arrayToPrettyString
from PIL import ImageTk, Image
import bing_image_download

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def viewListPage(window, title):
    tierList = getTierListByTitle(getUsername(),title)

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 322,
        width = 584,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        322.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        311.0,
        fill="#6D6B6B",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))

    from front_end_cud import deleteTierList
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: deleteTierList(window, title),
        relief="flat"
    )
    button_1.place(
        x=153.0,
        y=280.0,
        width=50.0,
        height=20.0
    )

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        267.0,
        fill="#424141",
        outline="")

    canvas.create_rectangle(
        20.0,
        49.0,
        568.0,
        116.0,
        fill="#262626",
        outline="")

#put images here:
    canvas.create_rectangle(
        86.0,
        55.0,
        561.0,
        109.0,
        fill="#D9D9D9",
        outline="")

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        59.5,
        83.0,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#FF7E7E",
        highlightthickness=0
    )
    entry_1.insert(INSERT, tierList["tiers"][0]["label1"][0]["name"])

    entry_1.place(
        x=37.0,
        y=64.0,
        width=45.0,
        height=36.0
    )

    canvas.create_rectangle(
        20.0,
        119.0,
        568.0,
        186.0,
        fill="#262626",
        outline="")

#put images here:
    canvas.create_rectangle(
        86.0,
        125.0,
        561.0,
        179.0,
        fill="#D9D9D9",
        outline="")

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        59.5,
        153.0,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#FF7E7E",
        highlightthickness=0
    )
    entry_2.insert(INSERT, tierList["tiers"][0]["label2"][0]["name"])
    entry_2.place(
        x=37.0,
        y=134.0,
        width=45.0,
        height=36.0
    )

    canvas.create_rectangle(
        20.0,
        189.0,
        568.0,
        256.0,
        fill="#262626",
        outline="")

    canvas.create_rectangle(
        86.0,
        195.0,
        561.0,
        249.0,
        fill="#D9D9D9",
        outline="")
    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        59.5,
        223.0,
        image=entry_image_3
    )
    entry_3 = Text(
        bd=0,
        bg="#FF7E7E",
        highlightthickness=0
    )
    entry_3.insert(INSERT, tierList["tiers"][0]["label3"][0]["name"])
    entry_3.place(
        x=37.0,
        y=204.0,
        width=45.0,
        height=36.0
    )

    canvas.create_text(
        342.0,
        282.0,
        anchor="nw",
        text="Name: " + title,
        fill="#000000",
        font=("Inter", 12 * -1)
    )

    # button_image_2 = PhotoImage(
    #     file=relative_to_assets("button_2.png"))
    # button_2 = Button(
    #     image=button_image_2,
    #     borderwidth=0,
    #     highlightthickness=0,
    #     command=lambda: print("TODO: SHARE"),
    #     relief="flat"
    # )
    # button_2.place(
    #     x=29.0,
    #     y=280.0,
    #     width=50.0,
    #     height=20.0
    # )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))

    from updateListPage.updateListPage import updateListPage
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: updateListPage(window, title),
        relief="flat"
    )
    button_3.place(
        x=91.0,
        y=280.0,
        width=50.0,
        height=20.0
    )

    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        34.0,
        fill="#5D5FEF",
        outline="")

    #
    canvas.create_text(
        136.0,
        2.0,
        anchor="nw",
        text="View List: " + title,
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))

    from browsePage.browsePage import browsePage
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: browsePage(window),
        relief="flat"
    )
    button_4.place(
        x=15.0,
        y=6.0,
        width=59.0,
        height=20.0
    )

#put images here:
    images1 = []
    images2 = []
    images3 = []
    i = 0
    xOffset = 0
    for query in tierList["tiers"][0]["label1"][0]["values"]:
        if (query == ""):
            continue
        path = "viewListPage/assets/bingImages/" + query.strip() + "/Image_1.*"
        imgPaths = glob.glob(path)

        #only download it if the result is not already downloaded
        if (len(imgPaths) == 0):
            bing_image_download.downloadImage(query)
            imgPaths = glob.glob(path)
        img = Image.open(imgPaths[0])
        img.thumbnail((80, 45))
        images1.append(ImageTk.PhotoImage(img))
        xOffset -= (80 - img.width) / 2
        entry_image_1 = canvas.create_image(130 + xOffset, 82, image=images1[i])
        xOffset += 40 + img.width / 2 + 10
        i += 1
    i = 0
    xOffset = 0
    for query in tierList["tiers"][0]["label2"][0]["values"]:
        if (query == ""):
            continue
        path = "viewListPage/assets/bingImages/" + query.strip() + "/Image_1.*"
        imgPaths = glob.glob(path)
        if (len(imgPaths) == 0):
            bing_image_download.downloadImage(query)
            imgPaths = glob.glob(path)
        img = Image.open(imgPaths[0])
        img.thumbnail((80, 45))
        images2.append(ImageTk.PhotoImage(img))
        xOffset -= (80 - img.width) / 2
        entry_image_1 = canvas.create_image(130 + xOffset, 82 + 70, image=images2[i])
        xOffset += 40 + img.width / 2 + 10
        i += 1
    i = 0
    xOffset = 0
    for query in tierList["tiers"][0]["label3"][0]["values"]:
        if (query == ""):
            continue
        path = "viewListPage/assets/bingImages/" + query.strip() + "/Image_1.*"
        imgPaths = glob.glob(path)
        if (len(imgPaths) == 0):
            bing_image_download.downloadImage(query)
            imgPaths = glob.glob(path)
        img = Image.open(imgPaths[0])
        img.thumbnail((80, 45), Image.ANTIALIAS)
        images3.append(ImageTk.PhotoImage(img))
        xOffset -= (80 - img.width) / 2
        entry_image_1 = canvas.create_image(130 + xOffset, 82 + 140, image=images3[i])
        xOffset += 40 + img.width / 2 + 10
        i += 1





    window.resizable(False, False)
    window.mainloop()
