
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import INSERT, Tk, Canvas, Entry, Text, Button, PhotoImage
from front_end_cud import getUsername

from front_end_r import getTierListByTitle
from util import arrayToPrettyString


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def updateListPage(window, title):
    tierList = getTierListByTitle(getUsername(),title)
    
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 322,
        width = 584,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        322.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        311.0,
        fill="#6D6B6B",
        outline="")

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        267.0,
        fill="#424141",
        outline="")

    canvas.create_rectangle(
        20.0,
        49.0,
        568.0,
        116.0,
        fill="#262626",
        outline="")

    #name
    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        471.5,
        290.5,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#D9D9D9",
        highlightthickness=0
    )
    entry_1.insert(INSERT, tierList["title"])
    
    entry_1.place(
        x=392.0,
        y=280.0,
        width=159.0,
        height=19.0
    )

    canvas.create_text(
        342.0,
        282.0,
        anchor="nw",
        text="Name:",
        fill="#000000",
        font=("Inter", 12 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    
    from front_end_cud import updateTierList
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: updateTierList(window, title, entry_1.get("1.0","end-1c"),entry_2.get("1.0","end-1c"), entry_3.get("1.0","end-1c"), entry_4.get("1.0","end-1c"), entry_5.get("1.0","end-1c"), entry_6.get("1.0","end-1c"), entry_7.get("1.0","end-1c")), #window, name, l1, e1,
        relief="flat"
    )
    button_1.place(
        x=29.0,
        y=280.0,
        width=50.0,
        height=20.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        472.5,
        83.0,
        image=entry_image_2
    )
    
    #first text box
    entry_2 = Text(
        bd=0,
        bg="#D9D9D9",
        highlightthickness=0
    )
    entry_2.insert(INSERT, arrayToPrettyString(tierList["tiers"][0]["label1"][0]["values"]))
    entry_2.place(
        x=394.0,
        y=70.0,
        width=157.0,
        height=24.0
    )

    canvas.create_rectangle(
        86.0,
        55.0,
        372.0,
        109.0,
        fill="#D9D9D9",
        outline="")

    #first red box
    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        59.5,
        83.0,
        image=entry_image_3
    )
    entry_3 = Text(
        bd=0,
        bg="#FF7E7E",
        highlightthickness=0
    )
    entry_3.insert(INSERT, tierList["tiers"][0]["label1"][0]["name"])
    
    entry_3.place(
        x=37.0,
        y=64.0,
        width=45.0,
        height=36.0
    )

    canvas.create_rectangle(
        20.0,
        119.0,
        568.0,
        186.0,
        fill="#262626",
        outline="")

    #second text box
    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        472.5,
        153.0,
        image=entry_image_4
    )
    entry_4 = Text(
        bd=0,
        bg="#D9D9D9",
        highlightthickness=0
    )
    entry_4.insert(INSERT, arrayToPrettyString(tierList["tiers"][0]["label2"][0]["values"]))
    entry_4.place(
        x=394.0,
        y=140.0,
        width=157.0,
        height=24.0
    )

    canvas.create_rectangle(
        86.0,
        125.0,
        372.0,
        179.0,
        fill="#D9D9D9",
        outline="")

    #second red box
    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_5.png"))
    entry_bg_5 = canvas.create_image(
        59.5,
        153.0,
        image=entry_image_5
    )
    entry_5 = Text(
        bd=0,
        bg="#FF7E7E",
        highlightthickness=0
    )
    entry_5.insert(INSERT, tierList["tiers"][0]["label2"][0]["name"])
    entry_5.place(
        x=37.0,
        y=134.0,
        width=45.0,
        height=36.0
    )

    canvas.create_rectangle(
        20.0,
        189.0,
        568.0,
        256.0,
        fill="#262626",
        outline="")

    #third text box
    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas.create_image(
        472.5,
        223.0,
        image=entry_image_6
    )
    entry_6 = Text(
        bd=0,
        bg="#D9D9D9",
        highlightthickness=0
    )
    entry_6.insert(INSERT, arrayToPrettyString(tierList["tiers"][0]["label3"][0]["values"]))
    entry_6.place(
        x=394.0,
        y=210.0,
        width=157.0,
        height=24.0
    )

    canvas.create_rectangle(
        86.0,
        195.0,
        372.0,
        249.0,
        fill="#D9D9D9",
        outline="")

    #third red box
    entry_image_7 = PhotoImage(
        file=relative_to_assets("entry_7.png"))
    entry_bg_7 = canvas.create_image(
        59.5,
        223.0,
        image=entry_image_7
    )
    entry_7 = Text(
        bd=0,
        bg="#FF7E7E",
        highlightthickness=0
    )
    entry_7.insert(INSERT, tierList["tiers"][0]["label3"][0]["name"])
    entry_7.place(
        x=37.0,
        y=204.0,
        width=45.0,
        height=36.0
    )

    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        34.0,
        fill="#5D5FEF",
        outline="")

    canvas.create_text(
        136.0,
        2.0,
        anchor="nw",
        text="Update List: " + title,
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))

    from viewListPage.viewListPage import viewListPage
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: viewListPage(window, title),
        relief="flat"
    )
    button_2.place(
        x=15.0,
        y=6.0,
        width=59.0,
        height=20.0
    )
    window.resizable(False, False)
    window.mainloop()
